["Nyhavn St.",
"Gamla Stan",
"Tivoli Park",
"Suomenlinna",
"Skeide i Ulstein ved skulen",
"Vestfjorden",
"Rådhusplassen",
"Aker Brygge",
"Slottet",
"Liseberg",
"Frognerparken",
"Akershus Festning",
"Vikingeskibsmuseet",
"Nidarosdomen",
"Vasa Museum",
"Kiruna Stadshus",
"Jökulsárlón",
"Fredensborg Slot",
"Fårö Fyr",
"Preikestolen",
"Kulturhuset",
"Nordkapp",
"Rauma",
"Røros",
"Træna",
"Ystad",
"Brandenburger Tor",
"Kölner Dom",
"Neuschwanstein Castle",
"Schlosspark",
"Heidelberg Altstadt",
"Potsdamer Platz",
"Schwarzwald",
"Rheinuferpromenade",
"Schloss Sanssouci",
"Bodensee",
"Berliner Fernsehturm",
"Zugspitze",
"Wartburg",
"Rügenkreidefelsen",
"Schweriner Schloss",
"Sanssouci Park",
"Loreley",
"Hamburger Hafen",
"Lübeck Altstadt",
"Romantische Straße",
"Rothenburg ob der Tauber",
"Bamberg Altstadt",
"Königssee",
"Saar Loop",
"Plaza Mayor",
"La Rambla",
"Alhambra",
"Mezquita-Catedral",
"El Mirador",
"Parque Güell",
"Teide National Park",
"Ibiza Old Town",
"Sagrada Familia",
"Plaza de la Constitución",
"Montjuïc",
"Cuenca Casas Colgadas",
"Plaza de España (Seville)",
"El Retiro Park",
"Alcazar of Segovia",
"Palacio de Bellas Artes",
"Castillo de Santa Barbara",
"Santiago de Compostela Cathedral",
"Las Canteras Beach",
"Tabernas Desert",
"Alcalá de Henares",
"Ronda",
"Costa del Sol",
"Cadaqués",
"Toledo",
"Красная площадь",
"Эрмитаж",
"Петропавловская крепость",
"Большой театр",
"Мичуринская",
"Экспоцентр",
"Арбатская площадь",
"Исаакиевский собор",
"Царицынское подворье",
"Парк Горького",
"Лужники",
"Петергоф",
"Суздаль",
"Владивосток",
"Екатеринбург",
"Нижний Новгород",
"Казанский Кремль",
"Байкал",
"Кольский полуостров",
"Волгоградская набережная",
"Кизи",
"Беловежская пуща",
"Кострома",
"Камчатские вулканы",
"Соловецкие острова"]