name = "LuxorMareyDiagram"
uuid = "3f0be14d-c4f6-498b-ba12-f13ee9a21c31"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]
version = "0.0.1"

[deps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Pango_jll = "36c8627f-9965-5494-a995-c6b170f724f3"

[compat]
Pango_jll = "=1.42.4"
julia = "1.7"
